language: cpp
compiler: gcc
dist: xenial
#sudo: true

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-add-repository ppa:sonkun/sfml-development -y
#  - sudo apt-get update -qq

install: 
 - apt search libsfml
 - apt search libsfml-dev
 - sudo apt install libsfml-dev
 # - sudo apt-get install -qq g++-5  
 # - sudo apt-get install libsfml-dev

script: 
 - qmake
 - make
 - ./travis_qmake_gcc_cpp11_sfml