language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # SFML
 - apt search libsfml
 - apt search libsfml-dev
 - sudo apt install libsfml-dev

script: 
 - qmake
 - make
 - ./travis_qmake_gcc_cpp11_sfml